name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update system
      run: sudo apt update
    - name: Install libev
      run: sudo apt install libev libev-dev
    - name: Install gcc-9
      run: sudo apt install gcc-9
    - name: Update alternatives
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60
    - name: mkdir
      run: mkdir build
      working-directory: /home/runner/work/pgagroal/pgagroal/
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: /home/runner/work/pgagroal/pgagroal/build/
    - name: make
      run: make
      working-directory: /home/runner/work/pgagroal/pgagroal/build/
