name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir
      run: mkdir /home/runner/work/pgagroal/build
    - name: cd
      run: cd /home/runner/work/pgagroal/build
    - name: list
      run: ls -la && ls -la ..
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: make
      
