name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir
      run: mkdir build
      working-directory: ./
    - name: cd
      run: cd build
      working-directory: ./
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: make
